services:
  backend:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map port 8080 on the host to port 8080 in the container
    environment:
      # Define any environment variables your application needs
      # These can override properties in application.properties or application.yml
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://db:5432/mydatabase
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: my-adminer-container
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  postgres_data:
