version: '3.8'

services:
  db:
    image: postgres:15
    container_name: budgeting-app-dev-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: budgeting-app-dev-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  postgres_dev_data: