spring:
  application:
    name: budgeting-app-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretForDevelopmentOnlyThisShouldBeLongerThan32Characters}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
